Auto commit

diff --git a/docs/Makefile.doc b/docs/Makefile.doc
--- a/docs/Makefile.doc
+++ b/docs/Makefile.doc
@@ -2,19 +2,22 @@ BOOK_NAME=$(shell basename $(CURDIR))
 TEXINPUTS=microtype:
 FONTSDIR=fonts
 TODAY=$(shell date --iso)
-TARGETS=$(BOOK_NAME)
+FORMAT=$(basename $(notdir $(FORMAT_FILE)))
+TARGET_NAME=$(BOOK_NAME)_${FORMAT}
 LATEX_INTERACTION=batchmode
 
-all: pdf
+all: $(TARGET_NAME).pdf
 
-pdf: $(addsuffix .pdf,$(TARGETS))
+$(TARGET_NAME).tex: $(BOOK_NAME).tex ../../${FORMAT_FILE}
+	@if [ "$(FORMAT)" = "" ]; then \
+	     echo "FORMAT ARG is required"; \
+	     exit 1; \
+	 fi
+	cat ../../${FORMAT_FILE} $(BOOK_NAME).tex > $@
 
-%.tex: %_doc.tex ../../formats/${format}.tex
-	cat ../../formats/${format}.tex $< > $@
-
-%.pdf: %.tex
+$(TARGET_NAME).pdf: $(TARGET_NAME).tex
 	OSFONTDIR=$(FONTSDIR) TEXINPUTS=$(TEXINPUTS) lualatex -shell-escape -interaction=$(LATEX_INTERACTION) $<
-	rm -f $<
+	rm -f $@
 	OSFONTDIR=$(FONTSDIR) TEXINPUTS=$(TEXINPUTS) lualatex -shell-escape -interaction=$(LATEX_INTERACTION) $<
 	rm -f $<
 
